Removed torch7 models
opencv/opencv_extra pull request #1097
Opened 2023-09-21 10:12 UTC by alexlyulkov

Removed torch7 models, because torch7 will not be supported in OpenCV 5:

removed Openface face recognition .t7 checkpoint
removed ENet image segmentation .net checkpoint
replaced Fast Neutral Style .t7 checkpoint by .onnx checkpoint

(this PR is a copy of  the closed PR #1096  but with a proper branch name)

2023-09-21 12:38 UTC, dkurt commented
Please also remove the following:

* https://github.com/opencv/opencv_extra/tree/5.x/testdata/dnn/torch
* https://github.com/opencv/opencv_extra/blob/5.x/testdata/dnn/lena_feathers.png
* https://github.com/opencv/opencv_extra/blob/5.x/testdata/dnn/lena_starry_night.png

2023-09-29 11:43 UTC, dkurt requested changes
@alexlyulkov, please remove monster-size https://github.com/alexlyulkov/opencv_extra/blob/al/remove-torch7-from-dnn/testdata/dnn/torch_enet_prob.npy and missed https://github.com/alexlyulkov/opencv_extra/blob/al/remove-torch7-from-dnn/testdata/dnn/generate_torch_models.py

2023-10-12 10:31 UTC, asmorkalov commented
@alexlyulkov Friendly reminder.

2023-10-13 06:45 UTC, opencv-alalek commented on testdata/dnn/download_models.py
> +        filename='mosaic-9.onnx'),
ONNX models should go to `onnx/models/`

2023-10-26 07:50 UTC, dkurt approved these changes

2023-10-26 08:27 UTC, merged